name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rspec:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { ruby_version: 2.5 }
          - { ruby_version: 2.7 }
          - { ruby_version: 3.0 }
          - { ruby_version: 3.1 }
          - { ruby_version: jruby }
    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby ${{ matrix.ruby_version }}
        uses: ruby/setup-ruby@v1
        with:
          bundler: 2
          ruby-version: ${{ matrix.ruby_version }}

      - name: Run specs
        run: |
          bundle install --jobs 4 --retry 3 --no-cache
          bundle exec rspec

      # - uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}

      - uses: mrexox/coveralls-github-action@feat/add-carryforward-flag
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ruby-${{ matrix.ruby_version }}
          path-to-lcov: ./coverage/lcov/sentry-sanitizer.lcov
          parallel: true

  coverage:
    needs: rspec
    name: Unit tests
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: mrexox/coveralls-github-action@feat/add-carryforward-flag
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          carryforward: "ruby-2.5,ruby-2.7,ruby-3.0,ruby-3.1,ruby-jruby"
          parallel-finished: true

